trigger:
  branches:
    include:
      - develop
pr:
  branches:
    include:
      - develop

pool:
 vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Application'

    steps:

     - checkout: self

     - script: |
        echo "Installing dependencies"
        displayName: 'Install dependencies'

     - script: |
        echo "Building the application"
        displayName: 'Build application'
     - script: |
        echo "Running tests"
        displayName: 'Run tests'
     - script: |
        echo "Running security scans"
        displayName: 'Run security scans' 

